apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCJr6wymhO+yNJAOzL6jxmwo6a8CBOH08NwDXlswQHV4Wr7DkQeYYMjRUB00MoHZSb4PeZr3Sr5bkyoeNgw4afgUdHRHl8+sedr5qEXK/Q+cYdBQL84fivIlKkBUNAflx5XsuHlKrguESB+ukC7AR5FPhdDILaV/+NHIqXgJl66A/X3JqdBEv7i+gI8XPeA3h5rELonrMN/Qb6gAfHqm5Uyu9TBb63aXkEsW/9PC38ARLqLDT2uONdtWePZ1q3rDubbLhy7NBPvUEY+DwMYHQe73qc1izG/GqNrIv4U51CrIYoXHwbxUofalCww3PJ4rdgQcoupe9ToJaZOcNnwkO7xDeNljfRtNEheUyBZfqs663Z+oDagY+rPNM9RjilDgJf+EFBGfDMl+jtwC/UyTqGQ3k0E7QQ4AWlcDCVDgCD2+4XVTMzHQkyCNpPdH/UgeDqco/A8MPyJC6nhBjxlsJ4O30ZNWR9TnTt7NyqzaOoE8SvPOoH9zX6dbjp288ycuhuyw8jSfCWEOzHe77VyIXQ/ssRRQYacREfExqH1KPUvtIESkkim4hctP/bkMsenEyjWKyDLhZo9BNVt7WU06nR79tpTAJQQOFhZysrrpiZtR1bGECR30KnMWeuAB+vrlRDNuJTo2KisTCxZPlKBiHAFyNcx0lQ87RGr8XPjGUi128UKzf00ztSzdtEkw0EqCg8am+ApEde2Vfj4xkq9iuScdzqgVzLKfDbOdFpbdxOBRCFFu2oqxeRu
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager-secret
      namespace: cert-manager
