apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA7l1WySXHcs0m51yDhmGeKNKFuyBnz/IuEA+6f3+CkxPj36DD2JudMjslghrpIExVgM0n+XI4vi34IknyuefaLfBqSGm7ZLFb+mGxvWkXtKXRKWktNw5dj6C4uFtkoBYFXDdNs2mHencrSjvUOnlCcKpjbXNvkVBWRs9Dv7Em7ePKK8jvrhqgspSrjDMmfGYRwgxI6/ZDxv31+OBj/GUJiWvCVuTCXRx2shSVPCjYlMWqcERLdKvISFAcby8K7Ome3Vex8VQb/a/cHUtcGE54giuRn46p3wE+hj6NPubkIzJ438Ig5zb6lRxvZCkl8eRJV+t1A7ZtVJtCzV9ojfI+Xx+zV8sLZUq0hti7mcPYcYr6ZAAKZ5nYMJRNZXV7LyIdyDflIXQIsBo7OQ8LZo7aMh52qS/KTbiUvRbdoCP9vm47Tvnh2BHE0fss16UyyCgCrP1g/1jXqQ6zMbT6Jo0Y6OSUCRpNA+70lPs19kracd0odh/SdmAx42gRf/a7N+ea9NTNqdXpOPnXLTpvFlpKzQEhQWjT63siHPG4oEdMLoflthTfL99dwGPb1wKJoAJotQ0akzUbmG51/DNFzWrGSJK+r2UE9fbwIHvS1nv/KPz/+iK7Fpccj9U68fh5mghC3Jgyj5zagi35V/nYGEgp4KHtO50BzMgDhN1P2sfhhuZgpDnHtDslFcJrRVvOHMxfqnlA09k9QD59XGNm793ODULYJvAUsLio9MUtlU8tNcBtVzyMu+nMW
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager-secret
      namespace: cert-manager
