apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mimir-agents-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: mimir-agents-ca
  secretName: mimir-agents-ca
  duration: 87600h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mimir-agents-ca
spec:
  ca:
    secretName: mimir-agents-ca
