apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-cert-manager
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/diegofnunesbr/cert-manager.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
